databases:
  - name: glow-db
    databaseName: glow_szcw
    user: glow_szcw_user
    plan: basic-256mb
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: '16'
    diskSizeGB: 1
services:
  - type: web
    name: glow-api
    runtime: node
    repo: https://github.com/trylinky/linky
    plan: starter
    envVars:
      - key: INSTAGRAM_CLIENT_SECRET
        sync: false
      - key: INSTAGRAM_CLIENT_ID
        sync: false
      - key: INSTAGRAM_CALLBACK_URL
        sync: false
      - key: INSTAGRAM_LEGACY_CLIENT_SECRET
        sync: false
      - key: INSTAGRAM_LEGACY_CALLBACK_URL
        sync: false
      - key: TIKTOK_CALLBACK_URL
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: INSTAGRAM_LEGACY_CLIENT_ID
        sync: false
      - key: THREADS_CLIENT_ID
        sync: false
      - key: THREADS_CLIENT_SECRET
        sync: false
      - key: THREADS_CALLBACK_URL
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URL
        sync: false
      - key: APP_FRONTEND_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: STRIPE_API_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: POSTHOG_API_KEY
        sync: false
      - key: APP_ENV
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: REACTIONS_TABLE_NAME
        sync: false
      - key: DIRECT_URL
        fromDatabase:
          name: linky-production
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: linky-production
          property: connectionString
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_AUTH_TOKEN
        sync: false
      - key: PORT
        sync: false
      - key: NODE_ENV
        sync: false
      - key: AUTH_TRUST_HOST
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: TINYBIRD_API_KEY
        sync: false
      - key: SCREENSHOT_API_KEY
        sync: false
      - key: AUTH_GOOGLE_CLIENT_ID
        sync: false
      - key: AUTH_GOOGLE_CLIENT_SECRET
        sync: false
      - key: AUTH_TIKTOK_CLIENT_ID
        sync: false
      - key: AUTH_TIKTOK_CLIENT_KEY
        sync: false
      - key: AUTH_TIKTOK_CLIENT_SECRET
        sync: false
      - key: AUTH_TWITTER_CLIENT_ID
        sync: false
      - key: AUTH_TWITTER_CLIENT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false

    region: frankfurt
    buildCommand:
      npm install && turbo run prisma:migrate prisma:generate --filter=@trylinky/prisma && turbo run build:api
      --filter=@trylinky/api
    startCommand: turbo run start:api
    domains:
      - api.lin.ky
version: '1'
